### PR TITLE
reduce BlocksOnCylindrical by using Generic

### PR DESCRIPTION
**Pull request by KrisThielemans**
This PR reduces the code-base by removing duplication between `ProjDataInfoBlocksOnCylindrical` and `ProjDataInfoGeneric`. The former was identical to the latter (before recent changes by @danieldeidda and @vietanhdao).

I have therefore first copied those changes to `ProjDataInfoGeneric`, and then essentially removed `ProjDataInfoBlocksOnCylindrical`. To make that a minimal change I've kept `ProjDataInfoBlocksOnCylindrical.h` which is now simply
```c++
using ProjDataInfoBlocksOnCylindrical = ProjDataInfoGeneric;
```

### CODE REVIEW

**Comment by KrisThielemans** [comment]
It's possible that this can be done for the `NoArcCorr` cases as well, but there are genuine differences on how the crystal-map is handled, so that'll have to come later.

**Comment by KrisThielemans** [comment]
@danieldeidda, the same test fails as before this PR of course. Unfortunately we cannot enable CI on this PR. It'll only run once we merge it to @pkhateri's `master`.

**Review by danieldeidda — APPROVED** [review]

**Comment by danieldeidda** [comment]
> 
> 
> @danieldeidda, the same test fails as before this PR of course. Unfortunately we cannot enable CI on this PR. It'll only run once we merge it to @pkhateri's `master`.

OK so this should not be changed in this PR as it's already correct in parisa:master

**Comment by KrisThielemans** [comment]
> > @danieldeidda, the same test fails as before this PR of course. Unfortunately we cannot enable CI on this PR. It'll only run once we merge it to @pkhateri's `master`.
> 
> OK so this should not be changed in this PR as it's already correct in parisa:master

sorry. the tests for parisa:master are failing on CI. (I forgot to press the "finish review" button).

**Comment by KrisThielemans** [comment]
@danieldeidda let me know if you're comfortable with merging this to `parisa:master` or first want to investigate the test failure

**Comment by danieldeidda** [comment]
> 
> 
> @danieldeidda let me know if you're comfortable with merging this to `parisa:master` or first want to investigate the test failure

I can investigate that also after you merge it with parisa:master probably easier

**Pull request merged**
