### PR TITLE
superblocks-case update in find_ML_normfactors3D.cxx and apply_normfactors3D.cxx

### PR DESCRIPTION
**Pull request by emikhay**
I copied find_ML_normfactors3D.cxx and apply_normfactors3D.cxx from UCL/STIR and then changed the num_physical_transaxial_crystals_per_block and num_physical_taxial_crystals_per_block calculation to "superblocks".

### CODE REVIEW

**Comment by emikhay** [comment]
@KrisThielemans @danieldeidda @VietAnhDao

**Comment by KrisThielemans** [comment]
sadly I don't think this can work. it'll probably need corresponding changes in MLnorm.cxx and possibly elsewhere. Also, copying lots of changes from another branch by hand removes appropriate attribution to the original author in git.

My feeling is that we'll either need to do this as a PR on `master` and then merge `master` here, or merge `master` here and then do a PR here.  I prefer the first option, as it makes the change more to the norm code more visible (as it doesn't have anything to do with blocksoncylindrical really) .

Of course, this assumes that we can merge `master` here. Wait for #2 to be merged and then attempt that?

**Comment by KrisThielemans** [comment]
This is now obsolete thanks to PR to `UCL/master`

**Comment by KrisThielemans** [comment]
Please close

**Comment by KrisThielemans** [comment]
@emikhay please close this one

**Pull request closed without merging**
